version: '3.9'
services:
  nginx:
    restart: always
    container_name: nginx
    image: nginx
    ports:
      - "8080:80"
    volumes: 
      - /d/Projects/Nodejs/shop-microservices/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - shop_microservices
networks:
  shop_microservices:
    name: shop_microservices
    driver: bridge
